name: Publicar no GitHub Pages

# Quando executar (push na branch main)
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

stages:
  - name: Testes
    jobs:
      - test
  - name: Deploy
    jobs:
      - deploy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm install
      - name: Executar testes
        run: npm run test

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm install
      # Faz o build do projeto
      - name: Exportar HTML, CSS e JS
        run: npm run build
      - name: Configurar páginas
        uses: actions/configure-pages@v5
      - name: Subir arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
